# mte-relay-client-flutter-pod/Example/ios/Podfile

source 'https://github.com/CocoaPods/Specs.git' 

workspace 'Runner.xcworkspace' 
platform :ios, '16.0'

# --- Load Flutter's Pod Helper (Crucial) ---
flutter_application_path = File.expand_path('..', __dir__) 
flutter_sdk_path = '/Users/gregwaggoner/development/flutter' 
flutter_pod_helper = File.join(flutter_sdk_path, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

if File.exist?(flutter_pod_helper)
  load flutter_pod_helper
else
  UI.warn "Flutter podhelper.rb not found at expected path: #{flutter_pod_helper}. " \
          "Flutter plugin integration might fail. Please verify your Flutter SDK installation."
end
# --- END Flutter's Pod Helper ---


target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'mte_relay_client_plugin', :path => '../../ios/mte_relay_client_plugin' 
  
  pod 'MteRelay', :git => 'https://github.com/Eclypses/mte-relay-client-ios.git', :tag => '4.4.1'
  
  pod 'Flutter' 

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # This is the ONLY place flutter_additional_ios_build_settings(target) should be called.
    flutter_additional_ios_build_settings(target) 

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
